### ISSUE TITLE
`sprintf` with `%c` 

### ISSUE THREAD

**Issue by IngeniariusSoftware** [objectionary/eo#1049]
code
```java
+alias org.eolang.txt.sprintf
+alias org.eolang.io.stdout

+package sandbox

[args...] > app
  stdout (sprintf "%c" (56.as-bytes.slice 7 1)) > @
```

current result:
```
Exception in thread "main" java.util.IllegalFormatConversionException: c != [B
        at java.util.Formatter$FormatSpecifier.failConversion(Unknown Source)
        at java.util.Formatter$FormatSpecifier.printCharacter(Unknown Source)
        at java.util.Formatter$FormatSpecifier.print(Unknown Source)
        at java.util.Formatter.format(Unknown Source)
        at java.util.Formatter.format(Unknown Source)
        at java.lang.String.format(Unknown Source)
        at EOorg.EOeolang.EOtxt.EOsprintf.lambda$new$0(EOsprintf.java:71)
        at org.eolang.AtComposite.get(AtComposite.java:73)
        at org.eolang.CachedPhi.get(CachedPhi.java:81)
        at org.eolang.PhDefault.attr(PhDefault.java:241)
        at org.eolang.PhLocated.attr(PhLocated.java:99)
        at org.eolang.PhOnce.attr(PhOnce.java:96)
        at org.eolang.PhOnce.attr(PhOnce.java:96)
        at org.eolang.PhOnce.attr(PhOnce.java:96)
        at org.eolang.PhNamed.attr(PhNamed.java:92)
        at org.eolang.PhSafe.attr(PhSafe.java:94)
        at org.eolang.Dataized.take(Dataized.java:81)
        at org.eolang.Param.weak(Param.java:101)
        at org.eolang.Param.strong(Param.java:80)
        at EOorg.EOeolang.EOio.EOstdout.lambda$new$0(EOstdout.java:66)
        at org.eolang.AtComposite.get(AtComposite.java:73)
        at org.eolang.CachedPhi.get(CachedPhi.java:81)
        at org.eolang.PhDefault.attr(PhDefault.java:241)
        at org.eolang.PhLocated.attr(PhLocated.java:99)
        at org.eolang.PhOnce.attr(PhOnce.java:96)
        at org.eolang.PhOnce.attr(PhOnce.java:96)
        at org.eolang.PhDefault.attr(PhDefault.java:242)
        at org.eolang.Dataized.take(Dataized.java:81)
        at org.eolang.Dataized.take(Dataized.java:121)
        at org.eolang.Main.run(Main.java:184)
        at org.eolang.Main.main(Main.java:92)
```

**Comment by yegor256** [comment]
@IngeniariusSoftware btw, I'm curious, why did you paste an image with stacktrace, instead of just copying the text?

**Comment by yegor256** [comment]
@Graur I think it's a bug in our implementation of `sprintf`. We should process the formatter string more carefully. When we meet `%c`, we should take the first byte of the provided argument. The same way, we should deal with other patterns.

**Comment by 0pdd** [comment]
@IngeniariusSoftware the puzzle [#1076](https://github.com/objectionary/eo/issues/1076) is still not solved.

**Comment by 0pdd** [comment]
@IngeniariusSoftware the only puzzle [#1076](https://github.com/objectionary/eo/issues/1076) is solved here.
