### ISSUE TITLE
AtFree is not thread safe

### ISSUE THREAD

**Issue by andreoss** [objectionary/eo#1119]
When being accessed from multiple threads `AtFree` thows this
```
Caused by: org.eolang.ExReadOnly: Error at "org.eolang.PhWithTest.Dummy#foo" attribute
	at org.eolang.AtNamed.put(AtNamed.java:116)
	at org.eolang.AtSafe.put(AtSafe.java:83)
	at org.eolang.PhWith.lambda$new$3(PhWith.java:86)
	at org.eolang.Data$Once.take(Data.java:116)
	at org.eolang.PhOnce.attr(PhOnce.java:96)
```

**Comment by andreoss** [comment]
@yegor256 Can i take this?

**Comment by yegor256** [comment]
@andreoss please, go ahead @Graur FYI

**Comment by andreoss** [comment]
@yegor256 This is fixed
