### ISSUE TITLE
Weak check for TimeOut delay in `ChRemoteTest`

### ISSUE THREAD

**Issue by MikhailLipanin** [objectionary/eo#1404]
[Here](https://github.com/objectionary/eo/blob/master/eo-maven-plugin/src/test/java/org/eolang/maven/ChRemoteTest.java#L43-L52)
there is a check before each Test, which depends on a constant `isReachable(1000)`. 
But on two computers there is 2 different ways of executing it:
- on first computer (Mac) all test skips due to this check
- on second computer (Windows) each test starts executing, which is wrong

both of computers have access to `home.objectionary.com`

```
org.opentest4j.AssertionFailedError: Unexpected exception type thrown, 
Expected :class java.lang.IllegalArgumentException
Actual   :class org.eolang.maven.ChText$NotFound
<Click to see difference>


	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:67)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:35)
	at org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:3083)
	at org.eolang.maven.ChRemoteTest.testCommitHashException(ChRemoteTest.java:78)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: org.eolang.maven.ChText$NotFound: The hash wasn't found for tag nonsense
	at org.eolang.maven.ChText.lambda$value$2(ChText.java:90)
	at org.cactoos.func.FuncOf.lambda$new$1(FuncOf.java:65)
	at org.cactoos.func.FuncOf.apply(FuncOf.java:78)
	at org.cactoos.scalar.ItemAt.lambda$new$1(ItemAt.java:118)
	at org.cactoos.scalar.Sticky.lambda$new$0(Sticky.java:73)
	at org.cactoos.func.StickyFunc.lambda$new$0(StickyFunc.java:70)
	at org.cactoos.func.StickyBiFunc.apply(StickyBiFunc.java:93)
	at org.cactoos.func.StickyFunc.apply(StickyFunc.java:77)
	at org.cactoos.scalar.Sticky.value(Sticky.java:79)
	at org.cactoos.scalar.ItemAt.value(ItemAt.java:127)
	at org.cactoos.scalar.FirstOf.value(FirstOf.java:104)
	at org.cactoos.scalar.Mapped.lambda$new$0(Mapped.java:58)
	at org.cactoos.scalar.ScalarEnvelope.value(ScalarEnvelope.java:53)
	at org.cactoos.text.TextOfScalar.asString(TextOfScalar.java:58)
	at org.cactoos.text.TextEnvelope.asString(TextEnvelope.java:51)
	at org.cactoos.text.TextEnvelope.asString(TextEnvelope.java:51)
	at org.cactoos.text.Split.lambda$new$0(Split.java:127)
	at org.cactoos.scalar.Checked.value(Checked.java:76)
	at org.cactoos.scalar.IoChecked.value(IoChecked.java:63)
	at org.cactoos.scalar.Unchecked.value(Unchecked.java:56)
	at org.cactoos.iterable.IterableOf.iterator(IterableOf.java:83)
	at org.cactoos.iterable.Mapped.lambda$new$0(Mapped.java:61)
	at org.cactoos.scalar.Checked.value(Checked.java:76)
	at org.cactoos.scalar.IoChecked.value(IoChecked.java:63)
	at org.cactoos.scalar.Unchecked.value(Unchecked.java:56)
	at org.cactoos.iterable.IterableOf.iterator(IterableOf.java:83)
	at org.cactoos.iterable.IterableEnvelope.iterator(IterableEnvelope.java:53)
	at org.cactoos.iterable.IterableEnvelope.iterator(IterableEnvelope.java:53)
	at org.cactoos.iterable.Filtered.lambda$new$0(Filtered.java:71)
	at org.cactoos.scalar.Checked.value(Checked.java:76)
	at org.cactoos.scalar.IoChecked.value(IoChecked.java:63)
	at org.cactoos.scalar.Unchecked.value(Unchecked.java:56)
	at org.cactoos.iterable.IterableOf.iterator(IterableOf.java:83)
	at org.cactoos.iterable.IterableEnvelope.iterator(IterableEnvelope.java:53)
	at org.cactoos.scalar.ItemAt.lambda$new$1(ItemAt.java:109)
	at org.cactoos.scalar.Sticky.lambda$new$0(Sticky.java:73)
	at org.cactoos.func.StickyFunc.lambda$new$0(StickyFunc.java:70)
	at org.cactoos.func.StickyBiFunc.apply(StickyBiFunc.java:93)
	at org.cactoos.func.StickyFunc.apply(StickyFunc.java:77)
	at org.cactoos.scalar.Sticky.value(Sticky.java:79)
	at org.cactoos.scalar.ItemAt.value(ItemAt.java:127)
	at org.cactoos.scalar.FirstOf.value(FirstOf.java:104)
	at org.cactoos.scalar.Mapped.lambda$new$0(Mapped.java:58)
	at org.cactoos.scalar.ScalarEnvelope.value(ScalarEnvelope.java:53)
	at org.cactoos.scalar.Checked.value(Checked.java:76)
	at org.cactoos.scalar.IoChecked.value(IoChecked.java:63)
	at org.cactoos.scalar.Unchecked.value(Unchecked.java:56)
	at org.eolang.maven.ChText.value(ChText.java:101)
	at org.eolang.maven.ChRemote.value(ChRemote.java:70)
	at org.eolang.maven.ChRemoteTest.lambda$testCommitHashException$0(ChRemoteTest.java:80)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:53)
	... 72 more
```

**Comment by MikhailLipanin** [comment]
#1411 fixes this
