### ISSUE TITLE
All CI pipelines are failed

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#1450]
All CICD pipelines failed by single problem:
```java
ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M7:test (default-test) on project eo-maven-plugin: 
[ERROR] 
[ERROR] Please refer to /Users/lombrozo/Workspace/EOlang/eo/eo-maven-plugin/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd '/Users/lombrozo/Workspace/EOlang/eo/eo-maven-plugin' && '/Users/lombrozo/Library/Java/JavaVirtualMachines/azul-11.0.12/Contents/Home/bin/java' '@{argLine}' '-Xss256M' '-jar' '/Users/lombrozo/Workspace/EOlang/eo/eo-maven-plugin/target/surefire/surefirebooter-20221114165834998_6.jar' '/Users/lombrozo/Workspace/EOlang/eo/eo-maven-plugin/target/surefire' '2022-11-14T16-58-25_457-jvmRun1' 'surefire-20221114165834998_4tmp' 'surefire_1-20221114165834998_5tmp'
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd '/Users/lombrozo/Workspace/EOlang/eo/eo-maven-plugin' && '/Users/lombrozo/Library/Java/JavaVirtualMachines/azul-11.0.12/Contents/Home/bin/java' '@{argLine}' '-Xss256M' '-jar' '/Users/lombrozo/Workspace/EOlang/eo/eo-maven-plugin/target/surefire/surefirebooter-20221114165834998_6.jar' '/Users/lombrozo/Workspace/EOlang/eo/eo-maven-plugin/target/surefire' '2022-11-14T16-58-25_457-jvmRun1' 'surefire-20221114165834998_4tmp' 'surefire_1-20221114165834998_5tmp'
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:714)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:311)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:268)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1334)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1167)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:931)
[ERROR]         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR]         at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR]         at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR]         at org.apache.maven.cli.MavenCli.execute(MavenCli.java:972)
[ERROR]         at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
[ERROR]         at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
```
I have the same problem on my working laptop.
How to reproduce: just call the `mvn clean package` command.
Failed pipelines:
https://github.com/objectionary/eo/actions/runs/3460928484/jobs/5777966547#step:5:246
https://github.com/objectionary/eo/actions/runs/3459912104/jobs/5775838307#step:5:246

**Comment by volodya-lombrozo** [comment]
@yegor256 assign to me, pls

**Comment by yegor256** [comment]
@volodya-lombrozo go ahead
