### ISSUE TITLE
Print human-readable message if object isn't found

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#1476]
I've wrote a simple `book.eo` program:
```eo
[] > app
  QQ.io.stdout > @
    QQ.txt.sprintf
      "Wake up, %s..."
      "Neo"
```
Then, in the terminal I wrote the next command:
```sh
eoc dataize book
```
And get the next exception in the console: 
```java
Exception in thread "main" java.lang.ClassNotFoundException: EObook
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at org.eolang.Main.run(Main.java:181)
	at org.eolang.Main.main(Main.java:98)
```
If you are a Java Developer, you can understand the problem - the `book` object doesn't exists and it's correct (because our object has the `app` name). I think it would be better to print more "human readable" message for developers. Something like a "'book' object doesn't exists, maybe you meant 'app'?"

**Comment by Graur** [comment]
@levBagryansky Can you help us with this? I suppose to add to `Main.run()` method some `try-catch` construction or to update `Main.main()` method exception catching.
