### ISSUE TITLE
Can't dataize eo program with `cage`: `IndexOutOfBoundsException`

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#1563]
I'm trying to dataize the next `eo` program:
```
+alias org.eolang.txt.sprintf
+alias org.eolang.io.stdout

[val] > container
  val > @

[] > loop
  cage 0 > index
  seq > @
    index.write container 1
    stdout
      sprintf
        "%s"
        index
    index.write container 2
    stdout
      sprintf
        "%s"
        index
    index.write container 3
    stdout
      sprintf
        "%s"
        index
    TRUE
```
Expected behaviour: program compiles and dataizes successfully.
Actual behaviour: I get the next exception:
```sh
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:459)
	at org.eolang.PhDefault.attr(PhDefault.java:231)
	at org.eolang.PhNamed.attr(PhNamed.java:87)
	at org.eolang.PhSafe.attr(PhSafe.java:83)
	at org.eolang.PhNamed.attr(PhNamed.java:87)
	at org.eolang.PhImmovable.attr(PhImmovable.java:80)
	at org.eolang.PhLocated.attr(PhLocated.java:94)
	at org.eolang.PhOnce.attr(PhOnce.java:91)
	at org.eolang.PhOnce.attr(PhOnce.java:91)
	at org.eolang.PhWith.lambda$new$3(PhWith.java:86)
	at org.eolang.Data$Once.lambda$take$0(Data.java:119)
	at java.base/java.util.concurrent.atomic.AtomicReference.updateAndGet(AtomicReference.java:209)
	at org.eolang.Data$Once.take(Data.java:115)
	at org.eolang.PhOnce.attr(PhOnce.java:96)
	at org.eolang.Dataized.take(Dataized.java:87)
	at EOorg.EOeolang.EOseq.lambda$new$0(EOseq.java:63)
	at org.eolang.AtComposite.get(AtComposite.java:73)
	at org.eolang.CachedPhi.get(CachedPhi.java:81)
	at org.eolang.PhDefault.attr(PhDefault.java:255)
	at org.eolang.PhLocated.attr(PhLocated.java:99)
	at org.eolang.PhOnce.attr(PhOnce.java:96)
	at org.eolang.PhOnce.attr(PhOnce.java:96)
	at org.eolang.PhOnce.attr(PhOnce.java:96)
	at org.eolang.PhOnce.attr(PhOnce.java:96)
	at org.eolang.PhOnce.attr(PhOnce.java:96)
	at org.eolang.PhOnce.attr(PhOnce.java:96)
	at org.eolang.PhOnce.attr(PhOnce.java:96)
	at org.eolang.PhOnce.attr(PhOnce.java:96)
	at org.eolang.PhDefault.attr(PhDefault.java:256)
	at org.eolang.Dataized.take(Dataized.java:87)
	at org.eolang.Dataized.take(Dataized.java:127)
	at org.eolang.Main.run(Main.java:190)
	at org.eolang.Main.main(Main.java:98)
```

**Comment by volodya-lombrozo** [comment]
Actually, I forgot to add parentheses:
```eo
+alias org.eolang.txt.sprintf
+alias org.eolang.io.stdout

[val] > container
  val > @

[] > loop
  cage 0 > index
  seq > @
    index.write (container 1)
    stdout
      sprintf
        "%s"
        index
    index.write (container 2)
    stdout
      sprintf
        "%s"
        index
    index.write (container 3)
    stdout
      sprintf
        "%s"
        index
    TRUE
```
But the error message in the console doesn't tell anything useful to find the problem. I took me some time to read code many times to locate the problem.

**Comment by yegor256** [comment]
@volodya-lombrozo maybe we should issue a warning, when this questionable syntax is used:

```
a b c
```

The warning should say: 

```
It is recommended to use vertical notation, since horizontal 
one may look ambiguous with two ore more arguments
```

**Comment by volodya-lombrozo** [comment]
@yegor256 I believe it's much better to add more context for the exception together with human readable message.

**Comment by yegor256** [comment]
@volodya-lombrozo definitely, let's add it to `PhDefault`
