### ISSUE TITLE
Incorrect groovy script behavior

### ISSUE THREAD

**Issue by levBagryansky** [objectionary/eo#1861]
I ran `mvn clean install` and when `eo-runtime` was been testing I stopped the process, added new directory to target and continued the process. 
```
...
[WARNING] XSL 'StUnhex' took 886ms (over 100ms)
^Z
[1]+  Остановлен    mvn clean install
tardis3@RyanGosling:~/eo$ mkdir eo-runtime/target/eo/7-something/
tardis3@RyanGosling:~/eo$ fg
mvn clean install
[WARNING] XSL 'rename-junit-inners' took 10s (over 100ms)
...
```
So I got the expected error
```
Exception in thread "main" Assertion failed: 

assert allowed.containsAll(directories)
       |       |           |
       |       false       [/home/tardis3/eo/eo-runtime/target/eo/6-transpile, /home/tardis3/eo/eo-runtime/target/eo/4-resolve, /home/tardis3/eo/eo-runtime/target/eo/7-something, /home/tardis3/eo/eo-runtime/target/eo/1-parse, /home/tardis3/eo/eo-runtime/target/eo/2-optimize, /home/tardis3/eo/eo-runtime/target/eo/5-pre, /home/tardis3/eo/eo-runtime/target/eo/3-pull]
       [/home/tardis3/eo/eo-runtime/target/eo/1-parse, /home/tardis3/eo/eo-runtime/target/eo/2-optimize, /home/tardis3/eo/eo-runtime/target/eo/3-pull, /home/tardis3/eo/eo-runtime/target/eo/4-resolve, /home/tardis3/eo/eo-runtime/target/eo/5-pre, /home/tardis3/eo/eo-runtime/target/eo/6-transpile]
``` 
But then the process does not end, but falls into livelock:
```
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)


```
This example looks may look unrealistic but everyone who will work with a new mojo will face this problem.
@volodya-lombrozo WDYT?

**Comment by volodya-lombrozo** [comment]
@levBagryansky I see two problems here.
1. Livelock if test is failed. Am I right?
2. The test shows that you added redundant directory.

As for 2 I believe we have to add a new directory to the groovy script as allowed folder. Of course we can change the test logic little bit and check only "required" directories and accept all other folders too, but in this case I'm afraid we can end up with some garbage in build directory.

**Comment by levBagryansky** [comment]
@volodya-lombrozo I agree. This issue is about livelock.
