### ISSUE TITLE
CleanMojoTest - flaky tests

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#2113]
Not so long time ago I've got the failed pipeline:
https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131

```java
Error:  Errors: 
[1584](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:1585)
Error:    AssembleMojoTest.assemblesTogether:80 » IllegalState org.apache.maven.plugin.MojoFailureException: 'org.eolang.maven.AssembleMojo@2f35bf66' execution failed
[1585](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:1586)
Error:    CleanMojoTest.makesFullCompilingLifecycleSuccessfully:99 » IllegalState org.apache.maven.plugin.MojoFailureException: 'org.eolang.maven.AssembleMojo@411b5ead' execution failed
[1586](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:1587)
[INFO] 
[1587](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:1588)
Error:  Tests run: 280, Failures: 0, Errors: 2, Skipped: 2
```

Actually both of the failed exceptions related to the same exception in `ResolveMojo`:
```java
Error:  org.eolang.maven.AssembleMojoTest.assemblesTogether(Path)  Time elapsed: 8.341 s  <<< ERROR!
[350](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:351)
java.lang.IllegalStateException: org.apache.maven.plugin.MojoFailureException: 'org.eolang.maven.AssembleMojo@2f35bf66' execution failed
[351](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:352)
	at org.eolang.maven.Moja.execute(Moja.java:124)
[352](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:353)
	at org.eolang.maven.AssembleMojoTest.assemblesTogether(AssembleMojoTest.java:80)
[353](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:354)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[354](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:355)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[355](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:356)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[356](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:357)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[357](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:358)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
[358](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:359)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
[359](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:360)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
[360](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:361)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
[361](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:362)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
[362](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:363)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
[363](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:364)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
[364](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:365)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
[365](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:366)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
[366](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:367)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
[367](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:368)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
[368](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:369)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
[369](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:370)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
[370](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:371)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
[371](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:372)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
[372](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:373)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
[373](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:374)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
[374](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:375)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
[375](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:376)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
[376](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:377)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
[377](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:378)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
[378](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:379)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
[379](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:380)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
[380](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:381)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
[381](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:382)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
[382](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:383)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
[383](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:384)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
[384](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:385)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:202)
[385](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:386)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
[386](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:387)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[387](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:388)
	at java.base/java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:396)
[388](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:389)
	at java.base/java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:721)
[389](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:390)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.joinConcurrentTasksInReverseOrderToEnableWorkStealing(ForkJoinPoolHierarchicalTestExecutorService.java:179)
[390](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:391)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:153)
[391](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:392)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
[392](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:393)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
[393](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:394)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
[394](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:395)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
[395](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:396)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
[396](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:397)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
[397](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:398)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
[398](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:399)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
[399](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:400)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:202)
[400](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:401)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
[401](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:402)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[402](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:403)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[403](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:404)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[404](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:405)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[405](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:406)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[406](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:407)
Caused by: org.apache.maven.plugin.MojoFailureException: 'org.eolang.maven.AssembleMojo@2f35bf66' execution failed
[407](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:408)
	at org.eolang.maven.SafeMojo.exitError(SafeMojo.java:341)
[408](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:409)
	at org.eolang.maven.SafeMojo.execute(SafeMojo.java:260)
[409](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:410)
	at org.eolang.maven.Moja.execute(Moja.java:120)
[410](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:411)
	... 54 more
[411](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:412)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: org.apache.maven.plugin.MojoFailureException: 'org.eolang.maven.ResolveMojo@3571b5a2' execution failed
[412](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:413)
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
[413](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:414)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:205)
[414](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:415)
	at org.eolang.maven.SafeMojo.execWithTimeout(SafeMojo.java:307)
[415](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:416)
	at org.eolang.maven.SafeMojo.execute(SafeMojo.java:234)
[416](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:417)
	... 55 more
[417](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:418)
Caused by: java.lang.IllegalStateException: org.apache.maven.plugin.MojoFailureException: 'org.eolang.maven.ResolveMojo@3571b5a2' execution failed
[418](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:419)
	at org.eolang.maven.Moja.execute(Moja.java:124)
[419](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:420)
	at org.eolang.maven.AssembleMojo.exec(AssembleMojo.java:212)
[420](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:421)
	at org.eolang.maven.SafeMojo.lambda$execWithTimeout$4(SafeMojo.java:304)
[421](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:422)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[422](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:423)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[423](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:424)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[424](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:425)
	at java.base/java.lang.Thread.run(Thread.java:829)
[425](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:426)
Caused by: org.apache.maven.plugin.MojoFailureException: 'org.eolang.maven.ResolveMojo@3571b5a2' execution failed
[426](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:427)
	at org.eolang.maven.SafeMojo.exitError(SafeMojo.java:341)
[427](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:428)
	at org.eolang.maven.SafeMojo.execute(SafeMojo.java:260)
[428](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:429)
	at org.eolang.maven.Moja.execute(Moja.java:120)
[429](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:430)
	... 6 more
[430](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:431)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
[431](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:432)
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
[432](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:433)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:205)
[433](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:434)
	at org.eolang.maven.SafeMojo.execWithTimeout(SafeMojo.java:307)
[434](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:435)
	at org.eolang.maven.SafeMojo.execute(SafeMojo.java:234)
[435](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:436)
	... 7 more
[436](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:437)
Caused by: java.lang.NullPointerException
[437](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:438)
	at java.base/java.util.stream.Collectors.lambda$groupingBy$53(Collectors.java:1134)
[438](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:439)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
[439](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:440)
	at java.base/java.util.LinkedList$ListItr.forEachRemaining(LinkedList.java:960)
[440](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:441)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
[441](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:442)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
[442](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:443)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[443](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:444)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
[444](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:445)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[445](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:446)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
[446](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:447)
	at org.eolang.maven.dependencies.DcsUniquelyVersioned.iterator(DcsUniquelyVersioned.java:61)
[447](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:448)
	at java.base/java.lang.Iterable.forEach(Iterable.java:74)
[448](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:449)
	at org.cactoos.list.ListOf.<init>(ListOf.java:65)
[449](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:450)
	at org.eolang.maven.ResolveMojo.deps(ResolveMojo.java:233)
[450](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:451)
	at org.eolang.maven.ResolveMojo.exec(ResolveMojo.java:151)
[451](https://github.com/objectionary/eo/actions/runs/5134268261/jobs/9238022131#step:5:452)
	... 5 more
```

**Comment by volodya-lombrozo** [comment]
I've tried to reproduce the problem several time and failed. Since all our pipelines works fine and don't fail with that exception we can close that issue. If the problem will happen again, we can re-open that issue.
