### ISSUE TITLE
Inconsistent Compiler Behavior + Source Code Edits Disregarded

### ISSUE THREAD

**Issue by Wissotsky** [objectionary/eo#2362]
Having issues following the eoc starting docs. But theyre quite puzzling so I will have to lay it out in as much detail as possible.

_all compilation is done via the `eoc dataize hello` command_ 

The example code provided by the docs looks like this:

```eolang
[args...] > hello
  QQ.io.stdout > @
    "Hello, world!\n"
```

At first I typed it in manually and it failed to compile due to me using a tab spacing of 4.

Then I decided to just copy the code from the docs directly which compiled completely fine and had the expected output of `Hello, world!`

I decided to make some edits to the code, aiming for a "hello, test!" outcome like this:

```eolang
[args...] > hello
  QQ.io.stdout > @
    "hello, test!\n"
```

But the first time I tried to compile it I got this error:

**Error Output:**

```
PS C:\...\eolang-experiments> eoc dataize hello
EO program assembled in C:\...\eolang-experiments\.eoc
Java sources generated in C:\...\eolang-experiments\.eoc\generated-sources
node:internal/fs/utils:3450 files generated so far...
    throw err;
    ^

    at Object.statSync (node:fs:1559:3)
    at count (C:\...\pnpm\global\5\.pnpm\eolang@0.13.4\node_modules\eolang\src\mvnw.js:145:16)
    at count (C:\...\pnpm\global\5\.pnpm\eolang@0.13.4\node_modules\eolang\src\mvnw.js:146:18)
    at print (C:\...\pnpm\global\5\.pnpm\eolang@0.13.4\node_modules\eolang\src\mvnw.js:163:45)
    at Timeout.check [as _onTimeout] (C:\...\pnpm\global\5\.pnpm\eolang@0.13.4\node_modules\eolang\src\mvnw.js:115:7)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7) {
  errno: -4058,
  syscall: 'stat',
  code: 'ENOENT',
  path: '.eoc\\classes\\EOhello.class'
}

Node.js v18.1.0
```

Then I decided to run the command again which seemed to have compiled successfully, but the output was still on `Hello, world!` instead of `hello, test!` as directed by the source code.

**Successful Output:**

```
PS C:\...\eolang-experiments> eoc dataize hello
EO objects registered in C:\...\eolang-experiments\.eoc\eo-foreign.json
EO program assembled in C:\...\eolang-experiments\.eoc
Java sources generated in C:\...\eolang-experiments\.eoc\generated-sources
Java .class files compiled into C:\...\eolang-experiments\.eoc
Executable JAR created at C:\...\eolang-experiments\.eoc\eoc.jar
Hello, world!
```

Important to note that every time I make any change to the source code I have to run the compilation twice for a "successful" output

CRLF/LF had no impact on the results

The jar file timestamp does get updated with each "successful" compilation.

env:
- OS: win10
- Editor: vscode
- eoc: Version: 0.13.4 (the latest one from npm)
- java: openjdk version "17.0.2" 2022-01-18 LTS
- pnpm: 8.6.11
- nodejs: v18.1.0.
- cargo: 1.73.0-nightly (7ac9416d8 2023-07-24)

**Comment by Wissotsky** [comment]
That seems to make it work fine.
