### ISSUE TITLE
Hello World Does Not Work

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#2656]
I get the code snippet from README:
```eo
+alias org.eolang.io.stdout
+alias org.eolang.txt.sprintf

[] > app
  (stdout (sprintf "Hello, %s!" "Jeffrey")) > @
```

run
```
eoc dataize app
```

and got the following exception:
```
EO version is 0.33.0
[eo:register] 4s; 0 files generated...
EO objects registered in /Users/lombrozo/Workspace/EOlang/temp/aliases/.eoc/eo-foreign.json
[eo:assemble] 4s; 1 files generated...[ERROR] Failed to parse '/Users/lombrozo/Workspace/EOlang/temp/aliases/app.eo:5': [5:43] no viable alternative at input '(stdout (sprintf "Hello, %s!" "Jeffrey")) ': "  (stdout (sprintf "Hello, %s!" "Jeffrey")) > @" (just logging, because of failOnError=false)
[ERROR] Failed to parse /Users/lombrozo/Workspace/EOlang/temp/aliases/app.eo (1 parsing errors)
[ERROR] 'org.eolang.maven.ParseMojo@47abbc20' execution failed
[ERROR] Failed to parse /Users/lombrozo/Workspace/EOlang/temp/aliases/app.eo (1 parsing errors)
[ERROR] Failed to execute goal org.eolang:eo-maven-plugin:0.33.0:assemble (default-cli) on project eoc: 'org.eolang.maven.AssembleMojo@6e6d4780' execution failed: java.lang.IllegalStateException: org.apache.maven.plugin.MojoFailureException: 'org.eolang.maven.ParseMojo@47abbc20' execution failed: java.io.UncheckedIOException: java.io.IOException: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Failed to parse /Users/lombrozo/Workspace/EOlang/temp/aliases/app.eo (1 parsing errors) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
/Users/lombrozo/.nvm/versions/node/v16.17.1/lib/node_modules/eolang/src/mvnw.js:82
          throw new Error(`The command "${cmd}" exited with #${code} code`);
          ^

Error: The command "/Users/lombrozo/.nvm/versions/node/v16.17.1/lib/node_modules/eolang/mvnw/mvnw eo:assemble -Deo.version=0.33.0 --quiet -Deo.targetDir=/Users/lombrozo/Workspace/EOlang/temp/aliases/.eoc -Deo.outputDir=/Users/lombrozo/Workspace/EOlang/temp/aliases/.eoc/classes -Deo.placed=/Users/lombrozo/Workspace/EOlang/temp/aliases/.eoc/eo-placed.csv -Deo.placedFormat=csv --batch-mode --update-snapshots --fail-fast" exited with #1 code
    at ChildProcess.<anonymous> (/Users/lombrozo/.nvm/versions/node/v16.17.1/lib/node_modules/eolang/src/mvnw.js:82:17)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1093:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)

```

**Comment by volodya-lombrozo** [comment]
Moreover, the exception message in even more confusing:
```
no viable alternative at input '(stdout (sprintf "Hello, %s!" "Jeffrey")) '
```
What should I do with it?

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you take a look, please?

**Comment by volodya-lombrozo** [comment]
@maxonfjvipon 
```eo
+alias org.eolang.io.stdout
+alias org.eolang.txt.sprintf

[] > app
  stdout (sprintf "Hello, %s!" "Jeffrey") > @
```

run `eoc dataize app --clean`

get:
```eo
EO version is 0.33.0
[eo:register] 3s; 0 files generated...
EO objects registered in /Users/lombrozo/Workspace/EOlang/temp/aliases/.eoc/eo-foreign.json
[eo:assemble] 25s; 3793 files generated...
EO program assembled in /Users/lombrozo/Workspace/EOlang/temp/aliases/.eoc
[eo:transpile] 15s; 4580 files generated...
Java sources generated in /Users/lombrozo/Workspace/EOlang/temp/aliases/.eoc/generated-sources
[compiler:compile] 6s; 4899 files generated...
Java .class files compiled into /Users/lombrozo/Workspace/EOlang/temp/aliases/.eoc
[jar:jar] 3s; 4947 files generated...
Executable JAR created at /Users/lombrozo/Workspace/EOlang/temp/aliases/.eoc/eoc.jar
Can't find Java object/package 'EOorg.EOeolang.EOtxt.EOsprintf' in EO package 'org.eolang.txt'
null
EOorg/EOeolang/EOtuple$EOempty
EOorg.EOeolang.EOtuple$EOempty
```

**Comment by maxonfjvipon** [comment]
@volodya-lombrozo this problem is related to new implementation of tuple (#2559) which was added in version `0.33.0`. Java code in `EOsprintf` does not match to this tuple implementation.

**Comment by maxonfjvipon** [comment]
@volodya-lombrozo core EO repository is quite unstable now. Many new features are being implemented, a lot of code is being cut out. And yes, it breaks other eo repos.

**Comment by maxonfjvipon** [comment]
@volodya-lombrozo `eo-runtime` 0.34.0 was uploaded to objectionary, your hello-world example should work now (without `sprintf` for now)

**Comment by volodya-lombrozo** [comment]
@maxonfjvipon 

With `sprintf`:
```eo
+alias org.eolang.io.stdout
+alias org.eolang.txt.sprintf

[] > app
  stdout (sprintf "Hello, %s!" "Jeffrey") > @
```

I get the following error:
```
EO version is 0.34.0
[eo:register] 8s; 0 files generated...
EO objects registered in /Users/lombrozo/Downloads/tmp/eofix/.eoc/eo-foreign.json
[eo:assemble] 5s; 4 files generated...[ERROR] Failed while trying to save to /Users/lombrozo/Downloads/tmp/eofix/.eoc/4-pull/org/eolang/txt/sprintf.eo
[ERROR] EO object 'org.eolang.txt.sprintf' is not found in this GitHub repository: https://github.com/objectionary/home. This means that you either misspelled the name of it or simply referred to your own local object somewhere in your code as if it was an object of 'org.eolang' package. Check the sources and make sure you always use +alias meta when you refer to an object outside of 'org.eolang', even if this object belongs to your package.
[ERROR] 'org.eolang.maven.PullMojo@4e3179cb' execution failed
[ERROR] Failed while trying to save to /Users/lombrozo/Downloads/tmp/eofix/.eoc/4-pull/org/eolang/txt/sprintf.eo
[ERROR] EO object 'org.eolang.txt.sprintf' is not found in this GitHub repository: https://github.com/objectionary/home. This means that you either misspelled the name of it or simply referred to your own local object somewhere in your code as if it was an object of 'org.eolang' package. Check the sources and make sure you always use +alias meta when you refer to an object outside of 'org.eolang', even if this object belongs to your package.
[ERROR] Failed to execute goal org.eolang:eo-maven-plugin:0.34.0:assemble (default-cli) on project eoc: 'org.eolang.maven.AssembleMojo@7d904ff1' execution failed: java.lang.IllegalStateException: org.apache.maven.plugin.MojoFailureException: 'org.eolang.maven.PullMojo@4e3179cb' execution failed: java.io.IOException: Failed while trying to save to /Users/lombrozo/Downloads/tmp/eofix/.eoc/4-pull/org/eolang/txt/sprintf.eo: EO object 'org.eolang.txt.sprintf' is not found in this GitHub repository: https://github.com/objectionary/home. This means that you either misspelled the name of it or simply referred to your own local object somewhere in your code as if it was an object of 'org.eolang' package. Check the sources and make sure you always use +alias meta when you refer to an object outside of 'org.eolang', even if this object belongs to your package. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
/Users/lombrozo/.nvm/versions/node/v16.17.1/lib/node_modules/eolang/src/mvnw.js:82
          throw new Error(`The command "${cmd}" exited with #${code} code`);
          ^

Error: The command "/Users/lombrozo/.nvm/versions/node/v16.17.1/lib/node_modules/eolang/mvnw/mvnw eo:assemble -Deo.version=0.34.0 --quiet -Deo.targetDir=/Users/lombrozo/Downloads/tmp/eofix/.eoc -Deo.outputDir=/Users/lombrozo/Downloads/tmp/eofix/.eoc/classes -Deo.placed=/Users/lombrozo/Downloads/tmp/eofix/.eoc/eo-placed.csv -Deo.placedFormat=csv --batch-mode --update-snapshots --fail-fast" exited with #1 code
    at ChildProcess.<anonymous> (/Users/lombrozo/.nvm/versions/node/v16.17.1/lib/node_modules/eolang/src/mvnw.js:82:17)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1093:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) 
```

**Comment by volodya-lombrozo** [comment]
@maxonfjvipon 

Without `sprintf`:

```eo
+alias org.eolang.io.stdout
+alias org.eolang.txt.sprintf

[] > app
  stdout "Hello, Jeffrey!" > @
```

I got the following error:
```
The directory /Users/lombrozo/Downloads/tmp/eofix/.eoc deleted
EO version is 0.34.0
[eo:register] 3s; 0 files generated...
EO objects registered in /Users/lombrozo/Downloads/tmp/eofix/.eoc/eo-foreign.json
[eo:assemble] 20s; 393 files generated...
EO program assembled in /Users/lombrozo/Downloads/tmp/eofix/.eoc
[eo:transpile] 3s; 393 files generated...[ERROR] java.lang.NullPointerException
[ERROR] Failed to execute goal org.eolang:eo-maven-plugin:0.34.0:transpile (default-cli) on project eoc: 'org.eolang.maven.TranspileMojo@67022ea' execution failed: java.io.UncheckedIOException: java.io.IOException: java.util.concurrent.ExecutionException: java.lang.NullPointerException -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
/Users/lombrozo/.nvm/versions/node/v16.17.1/lib/node_modules/eolang/src/mvnw.js:82
          throw new Error(`The command "${cmd}" exited with #${code} code`);
          ^

Error: The command "/Users/lombrozo/.nvm/versions/node/v16.17.1/lib/node_modules/eolang/mvnw/mvnw eo:transpile -Deo.version=0.34.0 --quiet -Deo.targetDir=/Users/lombrozo/Downloads/tmp/eofix/.eoc -Deo.generatedDir=/Users/lombrozo/Downloads/tmp/eofix/.eoc/generated-sources --batch-mode --update-snapshots --fail-fast" exited with #1 code
    at ChildProcess.<anonymous> (/Users/lombrozo/.nvm/versions/node/v16.17.1/lib/node_modules/eolang/src/mvnw.js:82:17)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1093:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
```

**Comment by maxonfjvipon** [comment]
@volodya-lombrozo https://github.com/objectionary/eoc/issues/205

**Comment by volodya-lombrozo** [comment]
@maxonfjvipon ?

**Comment by maxonfjvipon** [comment]
@volodya-lombrozo check above

**Comment by volodya-lombrozo** [comment]
@maxonfjvipon I've seen the link.  Please, add more context. Without this fix in `eoc` we won't be able to compile any `eo` program? or only this program? or what?

**Comment by maxonfjvipon** [comment]
@volodya-lombrozo any program, yes, it's a mandatory step

**Comment by maxonfjvipon** [comment]
@volodya-lombrozo still an issue?

**Comment by volodya-lombrozo** [comment]
@maxonfjvipon Yes, it is.
```
➜  eo-hello eoc dataize app
EO version is 0.35.1
[eo:register] 3s; 0 files generated...
EO objects registered in /Users/lombrozo/Downloads/tmp/javamain/eo-hello/.eoc/eo-foreign.json
[eo:assemble] 9s; 52 files generated...[ERROR] Failed to parse '/Users/lombrozo/Downloads/tmp/javamain/eo-hello/.eoc/4-pull/org/eolang/bytes.eo:66': [66:18] no viable alternative at input '^.right (x.neg)': "    ^.right (x.neg) > @"
[eo:assemble] 9s; 304 files generated...[ERROR] net.sf.saxon.style.XSLMessage@1a3e955: This transformation must be applied only after you remove @method attributes from objects, using 'wrap-method-calls.xsl'
[ERROR] #fatalError(): Processing terminated by xsl:message at line 82 in set-locators.xsl; SystemID: file:///org/eolang/parser/set-locators.xsl; Line#: 82; Column#: 36
[ERROR] Processing terminated by xsl:message at line 82 in set-locators.xsl
[ERROR] 'org.eolang.maven.ShakeMojo@7d8b6e1a' execution failed
[ERROR] Processing terminated by xsl:message at line 82 in set-locators.xsl
[ERROR] Failed to execute goal org.eolang:eo-maven-plugin:0.35.1:assemble (default-cli) on project eoc: 'org.eolang.maven.AssembleMojo@4b4eced1' execution failed: java.lang.IllegalStateException: org.apache.maven.plugin.MojoFailureException: 'org.eolang.maven.ShakeMojo@7d8b6e1a' execution failed: java.io.UncheckedIOException: java.io.IOException: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Failed to transform by net.sf.saxon.jaxp.TransformerImpl: Processing terminated by xsl:message at line 82 in set-locators.xsl; SystemID: file:///org/eolang/parser/set-locators.xsl; Line#: 82; Column#: 36 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
/Users/lombrozo/.nvm/versions/node/v16.17.1/lib/node_modules/eolang/src/mvnw.js:82
          throw new Error(`The command "${cmd}" exited with #${code} code`);
          ^

Error: The command "/Users/lombrozo/.nvm/versions/node/v16.17.1/lib/node_modules/eolang/mvnw/mvnw eo:assemble -Deo.version=0.35.1 --quiet -Deo.targetDir=/Users/lombrozo/Downloads/tmp/javamain/eo-hello/.eoc -Deo.outputDir=/Users/lombrozo/Downloads/tmp/javamain/eo-hello/.eoc/classes -Deo.placed=/Users/lombrozo/Downloads/tmp/javamain/eo-hello/.eoc/eo-placed.csv -Deo.placedFormat=csv --batch-mode --update-snapshots --fail-fast" exited with #1 code
    at ChildProcess.<anonymous> (/Users/lombrozo/.nvm/versions/node/v16.17.1/lib/node_modules/eolang/src/mvnw.js:82:17)
    at ChildProcess.emit (node:events:515:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)

Node.js v21.1.0
```

for 
```eo
+alias org.eolang.io.stdout
+alias org.eolang.txt.sprintf

[] > app
  stdout "Hello, Jeffrey!" > @
```

**Comment by maxonfjvipon** [comment]
@volodya-lombrozo in your program directory please do `eoc clean`, `rm -rf ~/.eo`, `npm update eolang -g` and run your program

**Comment by volodya-lombrozo** [comment]
@maxonfjvipon 
```sh
➜  vim app.eo
➜   la
total 8 -rw-r--r--  1 lombrozo  staff    99B Jan 30 11:11 app.eo
➜  eohello cat app.eo
+alias org.eolang.io.stdout
+alias org.eolang.txt.sprintf

[] > app
  stdout "Hello, Jeffrey!" > @ 
➜  eoc clean
The directory /Users/lombrozo/Downloads/tmp/eohello/.eoc deleted
➜   rm -rf ~/.eo
➜   npm update eolang -g

up to date in 649ms

29 packages are looking for funding
  run `npm fund` for details
➜   eoc dataize app
EO version is 0.35.1
[eo:register] 4s; 0 files generated...
EO objects registered in /Users/lombrozo/Downloads/tmp/eohello/.eoc/eo-foreign.json
[eo:assemble] 8s; 164 files generated...[ERROR] Failed to parse '/Users/lombrozo/Downloads/tmp/eohello/.eoc/4-pull/org/eolang/bytes.eo:66': [66:18] no viable alternative at input '^.right (x.neg)': "    ^.right (x.neg) > @"
[ERROR] net.sf.saxon.style.XSLMessage@4a41ba49: This transformation must be applied only after you remove @method attributes from objects, using 'wrap-method-calls.xsl'
[ERROR] #fatalError(): Processing terminated by xsl:message at line 82 in set-locators.xsl; SystemID: file:///org/eolang/parser/set-locators.xsl; Line#: 82; Column#: 36
[ERROR] Processing terminated by xsl:message at line 82 in set-locators.xsl
[eo:assemble] 8s; 310 files generated...[ERROR] 'org.eolang.maven.ShakeMojo@487b834b' execution failed
[ERROR] Processing terminated by xsl:message at line 82 in set-locators.xsl
[ERROR] Failed to execute goal org.eolang:eo-maven-plugin:0.35.1:assemble (default-cli) on project eoc: 'org.eolang.maven.AssembleMojo@4b4eced1' execution failed: java.lang.IllegalStateException: org.apache.maven.plugin.MojoFailureException: 'org.eolang.maven.ShakeMojo@487b834b' execution failed: java.io.UncheckedIOException: java.io.IOException: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Failed to transform by net.sf.saxon.jaxp.TransformerImpl: Processing terminated by xsl:message at line 82 in set-locators.xsl; SystemID: file:///org/eolang/parser/set-locators.xsl; Line#: 82; Column#: 36 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
/Users/lombrozo/.nvm/versions/node/v16.17.1/lib/node_modules/eolang/src/mvnw.js:82
          throw new Error(`The command "${cmd}" exited with #${code} code`);
          ^

Error: The command "/Users/lombrozo/.nvm/versions/node/v16.17.1/lib/node_modules/eolang/mvnw/mvnw eo:assemble -Deo.version=0.35.1 --quiet -Deo.targetDir=/Users/lombrozo/Downloads/tmp/eohello/.eoc -Deo.outputDir=/Users/lombrozo/Downloads/tmp/eohello/.eoc/classes -Deo.placed=/Users/lombrozo/Downloads/tmp/eohello/.eoc/eo-placed.csv -Deo.placedFormat=csv --batch-mode --update-snapshots --fail-fast" exited with #1 code
    at ChildProcess.<anonymous> (/Users/lombrozo/.nvm/versions/node/v16.17.1/lib/node_modules/eolang/src/mvnw.js:82:17)
    at ChildProcess.emit (node:events:515:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)

Node.js v21.1.0


```

**Comment by volodya-lombrozo** [comment]
With `eoc:0.15.1` I'm getting the following exception:
```
EO objects registered in .eoc/eo-foreign.json
Assembling into .eoc
EO program assembled in .eoc
[ERROR] net.sf.saxon.style.XSLMessage@52259724: Errors identified:
  /Users/lombrozo/Downloads/tmp/eohello/app.eo, 2: The alias "org.eolang.txt.sprintf" is not used;
[ERROR] #fatalError(): Processing terminated by xsl:message at line 31 in fail-on-errors.xsl; SystemID: file:///org/eolang/parser/fail-on-errors.xsl; Line#: 31; Column#: 34
[ERROR] Processing terminated by xsl:message at line 31 in fail-on-errors.xsl
[ERROR] Failed to execute goal org.eolang:eo-maven-plugin:0.34.1:verify (default-cli) on project eoc: 'org.eolang.maven.VerifyMojo@6f044c58' execution failed: java.io.UncheckedIOException: java.io.IOException: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Failed to transform by net.sf.saxon.jaxp.TransformerImpl: ; Processing terminated by xsl:message at line 31 in fail-on-errors.xsl; SystemID: file:///org/eolang/parser/fail-on-errors.xsl; Line#: 31; Column#: 34 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
The command "/usr/local/lib/node_modules/eolang/mvnw/mvnw eo:verify -Deo.version=0.34.1 -Deo.hash=0.34.1 --quiet -Deo.sourcesDir=/Users/lombrozo/Downloads/tmp/eohello -Deo.targetDir=/Users/lombrozo/Downloads/tmp/eohello/.eoc -Deo.outputDir=/Users/lombrozo/Downloads/tmp/eohello/.eoc/classes -Deo.generatedDir=/Users/lombrozo/Downloads/tmp/eohello/.eoc/generated-sources -Deo.placed=/Users/lombrozo/Downloads/tmp/eohello/.eoc/eo-placed.csv -Deo.placedFormat=csv --batch-mode --color=never --update-snapshots --fail-fast --strict-checksums" exited with #1 code
```

**Comment by maxonfjvipon** [comment]
@volodya-lombrozo `The alias "org.eolang.txt.sprintf" is not used` - just remove the unused alias

**Comment by volodya-lombrozo** [comment]
@maxonfjvipon Now it works like a charm. Thank you. The original problem was in outdated `eoc` version. I had `eoc:0.12.0`, but the working version is `eoc:0.15.1`. At least for now. 
BTW, the ` npm update eolang -g` didn't update the `eoc` version. I had to remove the binary manually and then install `eolang` packages again.
