### ISSUE TITLE
build is broken: NPE in CommitHashesMap.fromTable

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#2699]
See https://github.com/objectionary/eo/actions/runs/7199045411/job/19609846078

```
java.lang.NullPointerException
	at org.cactoos.text.TextOfScalar.asString(TextOfScalar.java:58)
	at org.cactoos.text.TextEnvelope.asString(TextEnvelope.java:51)
	at org.cactoos.text.TextEnvelope.asString(TextEnvelope.java:51)
	at org.cactoos.text.Split.lambda$new$0(Split.java:127)
	at org.cactoos.scalar.Checked.value(Checked.java:76)
	at org.cactoos.scalar.IoChecked.value(IoChecked.java:63)
	at org.cactoos.scalar.Unchecked.value(Unchecked.java:56)
	at org.cactoos.iterable.IterableOf.iterator(IterableOf.java:83)
	at org.cactoos.iterable.Mapped.lambda$new$0(Mapped.java:61)
	at org.cactoos.scalar.Checked.value(Checked.java:76)
	at org.cactoos.scalar.IoChecked.value(IoChecked.java:63)
	at org.cactoos.scalar.Unchecked.value(Unchecked.java:56)
	at org.cactoos.iterable.IterableOf.iterator(IterableOf.java:83)
	at org.cactoos.iterable.IterableEnvelope.iterator(IterableEnvelope.java:53)
	at org.cactoos.iterable.IterableEnvelope.iterator(IterableEnvelope.java:53)
	at org.cactoos.iterable.Mapped.lambda$new$0(Mapped.java:61)
	at org.cactoos.scalar.Checked.value(Checked.java:76)
	at org.cactoos.scalar.IoChecked.value(IoChecked.java:63)
	at org.cactoos.scalar.Unchecked.value(Unchecked.java:56)
	at org.cactoos.iterable.IterableOf.iterator(IterableOf.java:83)
	at org.cactoos.iterable.IterableEnvelope.iterator(IterableEnvelope.java:53)
	at org.cactoos.map.MapOf.make(MapOf.java:189)
	at org.cactoos.map.MapOf.<init>(MapOf.java:176)
	at org.eolang.maven.hash.CommitHashesMap.fromTable(CommitHashesMap.java:93)
	at org.eolang.maven.hash.CommitHashesMap.<init>(CommitHashesMap.java:69)
	at org.eolang.maven.hash.CommitHashesMap.<init>(CommitHashesMap.java:53)
	at org.eolang.maven.SafeMojo.<init>(SafeMojo.java:219)
	at org.eolang.maven.ParseMojo.<init>(ParseMojo.java:65)
```

**Comment by yegor256** [comment]
@maxonfjvipon please, take a look
