### ISSUE TITLE
Unreadable exception  Ex EOorg.EOeolang.EOstringν62

### ISSUE THREAD

**Issue by levBagryansky** [objectionary/eo#2772]
The following stack trace does not help to find out the mistake in eo code:
```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.154 s <<< FAILURE! -- in EOorg.EOeolang.EOsqrt_trashTest
[ERROR] EOorg.EOeolang.EOsqrt_trashTest.works -- Time elapsed: 0.087 s <<< ERROR!
EOorg.EOeolang.EOerror$ExError: EOorg.EOeolang.EOstringν62
        at org.eolang.PhSafe.attr(PhSafe.java:92)
        at org.eolang.PhImmovable.attr(PhImmovable.java:81)
        at org.eolang.PhOnce.attr(PhOnce.java:92)
        at org.eolang.PhOnce.attr(PhOnce.java:92)
        at org.eolang.PhLocated.attr(PhLocated.java:118)
        at org.eolang.PhNamed.attr(PhNamed.java:88)
        at org.eolang.PhSafe.attr(PhSafe.java:90)
        at org.eolang.PhImmovable.attr(PhImmovable.java:81)
        at org.eolang.PhOnce.attr(PhOnce.java:92)
        at org.eolang.PhLocated.attr(PhLocated.java:118)
        at org.eolang.PhMethod.lambda$new$0(PhMethod.java:43)
        at org.eolang.Data$Once.lambda$take$0(Data.java:120)

```

**Comment by levBagryansky** [comment]
@maxonfjvipon I guess I can solve it

**Comment by maxonfjvipon** [comment]
@levBagryansky sure, go ahead
