### ISSUE TITLE
`StrictXmir.java` throws `XML document structures must start and end within the same entity`

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#3726]
I've updated the `jeo-maven-plugin` up to `0.49.2` version: https://github.com/objectionary/jeo-maven-plugin/pull/942/commits/a0ddd5089a14be7b45e37590cb05ecc55da4b610

Now `StrictXmir` throws the following exception:

```java
Caused by: java.lang.IllegalStateException: org.xml.sax.SAXParseException; systemId: file:////Users/runner/work/jeo-maven-plugin/jeo-maven-plugin/target/its/spring-fat/target/xsd/XMIR-0.49.2.xsd; lineNumber: 339; columnNumber: 29; XML document structures must start and end within the same entity.
    at com.jcabi.xml.StrictXML.validate (StrictXML.java:299)
    at com.jcabi.xml.StrictXML.<init> (StrictXML.java:93)
    at com.jcabi.xml.StrictXML.<init> (StrictXML.java:84)
    at com.jcabi.xml.StrictXML.<init> (StrictXML.java:74)
    at org.eolang.parser.StrictXmir.<init> (StrictXmir.java:96)
    at org.eolang.parser.StrictXmir.<init> (StrictXmir.java:81)
    at org.eolang.jeo.representation.VerifiedEo.asXml (VerifiedEo.java:71)
    at org.eolang.jeo.representation.MeasuredEo.asXml (MeasuredEo.java:58)
    at org.eolang.jeo.representation.BytecodeRepresentation.toEO (BytecodeRepresentation.java:117)
    at org.eolang.jeo.Disassembling.transform (Disassembling.java:86)
    at org.eolang.jeo.Caching.tryTransform (Caching.java:93)
    at org.eolang.jeo.Caching.transform (Caching.java:63)
    at org.eolang.jeo.Logging.transform (Logging.java:83)
    at org.eolang.jeo.Disassembler.disassemble (Disassembler.java:113)
    at org.eolang.jeo.ParallelTranslator.translate (ParallelTranslator.java:70)
    at java.util.stream.ReferencePipeline$3$1.accept (ReferencePipeline.java:195)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining (ArrayList.java:1655)
    at java.util.stream.AbstractPipeline.copyInto (AbstractPipeline.java:484)
    at java.util.stream.ForEachOps$ForEachTask.compute (ForEachOps.java:290)
    at java.util.concurrent.CountedCompleter.exec (CountedCompleter.java:746)
    at java.util.concurrent.ForkJoinTask.doExec (ForkJoinTask.java:290)
    at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec (ForkJoinPool.java:1020)
    at java.util.concurrent.ForkJoinPool.scan (ForkJoinPool.java:1656)
    at java.util.concurrent.ForkJoinPool.runWorker (ForkJoinPool.java:1594)
    at java.util.concurrent.ForkJoinWorkerThread.run (ForkJoinWorkerThread.java:183)
Caused by: org.xml.sax.SAXParseException: XML document structures must start and end within the same entity.
    at org.apache.xerces.jaxp.validation.Util.toSAXParseException (Unknown Source)
    at org.apache.xerces.jaxp.validation.DOMValidatorHelper.validate (Unknown Source)
    at org.apache.xerces.jaxp.validation.ValidatorImpl.validate (Unknown Source)
    at javax.xml.validation.Validator.validate (Validator.java:124)
    at com.jcabi.xml.StrictXML.validate (StrictXML.java:282)
    at com.jcabi.xml.StrictXML.<init> (StrictXML.java:93)
    at com.jcabi.xml.StrictXML.<init> (StrictXML.java:84)
    at com.jcabi.xml.StrictXML.<init> (StrictXML.java:74)
    at org.eolang.parser.StrictXmir.<init> (StrictXmir.java:96)
    at org.eolang.parser.StrictXmir.<init> (StrictXmir.java:81)
    at org.eolang.jeo.representation.VerifiedEo.asXml (VerifiedEo.java:71)
    at org.eolang.jeo.representation.MeasuredEo.asXml (MeasuredEo.java:58)
    at org.eolang.jeo.representation.BytecodeRepresentation.toEO (BytecodeRepresentation.java:117)
    at org.eolang.jeo.Disassembling.transform (Disassembling.java:86)
    at org.eolang.jeo.Caching.tryTransform (Caching.java:93)
    at org.eolang.jeo.Caching.transform (Caching.java:63)
    at org.eolang.jeo.Logging.transform (Logging.java:83)
    at org.eolang.jeo.Disassembler.disassemble (Disassembler.java:113)
    at org.eolang.jeo.ParallelTranslator.translate (ParallelTranslator.java:70)
    at java.util.stream.ReferencePipeline$3$1.accept (ReferencePipeline.java:195)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining (ArrayList.java:1655)
    at java.util.stream.AbstractPipeline.copyInto (AbstractPipeline.java:484)
    at java.util.stream.ForEachOps$ForEachTask.compute (ForEachOps.java:290)
    at java.util.concurrent.CountedCompleter.exec (CountedCompleter.java:746)
    at java.util.concurrent.ForkJoinTask.doExec (ForkJoinTask.java:290)
    at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec (ForkJoinPool.java:1020)
    at java.util.concurrent.ForkJoinPool.scan (ForkJoinPool.java:1656)
    at java.util.concurrent.ForkJoinPool.runWorker (ForkJoinPool.java:1594)
    at java.util.concurrent.ForkJoinWorkerThread.run (ForkJoinWorkerThread.java:183)
```

Here you can find the failed pipeline: https://github.com/objectionary/jeo-maven-plugin/actions/runs/12433923236/job/34716515344?pr=942

All files and directories during the failure: https://github.com/objectionary/jeo-maven-plugin/actions/runs/12433923236/artifacts/2349006127

XSD file: 
[XMIR-0.49.2.xsd.txt](https://github.com/user-attachments/files/18220749/XMIR-0.49.2.xsd.txt)

Log file: 
[build.log.txt](https://github.com/user-attachments/files/18220754/build.log.txt)

**Comment by volodya-lombrozo** [comment]
@yegor256 @maxonfjvipon Could you take a look, please?

**Comment by volodya-lombrozo** [comment]
Critical blocker for https://github.com/objectionary/jeo-maven-plugin/pull/942

**Comment by volodya-lombrozo** [comment]
@maxonfjvipon, do you have any progress here? This is a somewhat urgent matter.

**Comment by maxonfjvipon** [comment]
@volodya-lombrozo yes, working on it, the main problem is the `jcabi-xml` thread unsafety. Should be fixed today

**Comment by yegor256** [comment]
@maxonfjvipon jcabi-xml 0.33.3 was released, you can try to use it

**Comment by volodya-lombrozo** [comment]
@yegor256 I can't. I need a fresh version of `eo` that uses `jcabi-xml:0.33.3`. Otherwise I'm getting the following exception:

```java
java.lang.NoSuchMethodError: 'java.util.Collection com.jcabi.xml.XML.validate()'

	at org.eolang.parser.StrictXmir.validate(StrictXmir.java:144)
	at org.eolang.jeo.representation.XmirRepresentation.toBytecode(XmirRepresentation.java:154)
	at org.eolang.jeo.representation.XmirRepresentationTest.convertsHelloWordEoRepresentationIntoBytecode(XmirRepresentationTest.java:133)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

`StrictXmir` in eo has the following method:

```java
    @Override
    public Collection<SAXParseException> validate() {
        return this.xml.validate();
    }
```
Please, release a new version of eo.

**Comment by yegor256** [comment]
@rultor release, tag is `0.49.3`

**Comment by yegor256** [comment]
@volodya-lombrozo try version 0.49.3 please

**Comment by volodya-lombrozo** [comment]
@yegor256 What is the current API of `StrictXmir`? How should I use it? 
Current implementation gives me compile time errors:

```java
new StrictXmir(new XMLDocument(xmir)).validate();
```

**Comment by maxonfjvipon** [comment]
@volodya-lombrozo we've [changed](https://github.com/jcabi/jcabi-xml/pull/285/files#diff-9485f7e96e60727ad3ea72e693bba4128e7670afb895077f0a81e8cfb18da2ac) the `XML` interface. You don't need to use `.validate()` explicitly on `StrictXmir`, it will be done automatically once you "touch" the object

**Comment by volodya-lombrozo** [comment]
> @volodya-lombrozo we've [changed](https://github.com/jcabi/jcabi-xml/pull/285/files#diff-9485f7e96e60727ad3ea72e693bba4128e7670afb895077f0a81e8cfb18da2ac) the `XML` interface. You don't need to use `.validate()` explicitly on `StrictXmir`, it will be done automatically once you "touch" the object. So if you do `.validate()` it'll just validate it twice

@maxonfjvipon I've read the code. Since I don't use the `XML` interface and I don't need to process `StrictXmir` somewhere else, In order to validate it, I need to use `new StrictXml(new XMLDocument(xml)).inner()`. To me, this API is counterintuitive. Why do we need open `validate` method then? @yegor256 Do you agree with such a design?

**Comment by yegor256** [comment]
@volodya-lombrozo this is a good question, but more related to jcabi-xml repository. Quick answer: in order to validate `XML`, you use `xml.validate()` (returns a list of errors); in order to validate+log, you decorate `StrictXML(xml)` and then use it, expecting an exception later (when you call `.inner()`, for example.

**Comment by volodya-lombrozo** [comment]
@yegor256 I can't use `xml.validate()` without an `XSD` document. Moreover, what is the difference between `StrictXmir` and `StrictXML` classes then? I thought, `StrictXmir` is supposed to know about the `XSD` it validates against, but seems I'm wrong.

**Comment by volodya-lombrozo** [comment]
@yegor256 @maxonfjvipon Ok, it's a separate story. Anyway the new solution doesn't work:
https://github.com/objectionary/eo/issues/3760
