### ISSUE TITLE
Problems with access to parent's objects

### ISSUE THREAD

**Issue by someilay** [objectionary/eo#495]
Code:
```
+package sandbox
+alias sandbox.std.class__Object
+alias stdout org.eolang.io.stdout
+alias sprintf org.eolang.txt.sprintf
+alias org.eolang.gray.cage

[] > classA
  class__Object > @

  [i] > new
    [] > this
      class__Object.new > super
      super > @
      classA > static
      memory > i

      [x] > f
        seq > @
          ^.i.write x

      [y] > g
        seq > @
          ^.f (y.add 1)

    seq > @
      this.i.write i
      this

[args...] > app
  cage > a
  seq > @
    a.write
      classA.new 42
    stdout
      sprintf "%d\n" (a.i)
    a.f 43
    stdout
      sprintf "%d\n" (a.i)
    a.g 44
    stdout
      sprintf "%d\n" (a.i)
```

Error during runtime:
```
42
Exception in thread "main" org.eolang.Attr$StillAbstractException: Error at "EOorg.EOeolang.EOint#write" attribute
	at org.eolang.AtNamed.get(AtNamed.java:79)
	at org.eolang.PhMethod.lambda$new$0(PhMethod.java:42)
	at org.eolang.Data$Once.take(Data.java:95)
	at org.eolang.PhOnce.copy(PhOnce.java:81)
	at org.eolang.Data$Once.take(Data.java:95)
	at org.eolang.PhOnce.attr(PhOnce.java:91)
	at org.eolang.PhWith.lambda$new$3(PhWith.java:72)
	at org.eolang.Data$Once.take(Data.java:95)
	at org.eolang.PhOnce.attr(PhOnce.java:96)
	at org.eolang.PhDefault.attr(PhDefault.java:208)
	at org.eolang.PhOnce.attr(PhOnce.java:96)
	at org.eolang.PhOnce.attr(PhOnce.java:96)
	at org.eolang.PhDefault.attr(PhDefault.java:208)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhOnce.attr(PhOnce.java:96)
	at org.eolang.PhOnce.attr(PhOnce.java:96)
	at org.eolang.Dataized.take(Dataized.java:71)
	at EOorg.EOeolang.EOseq.lambda$new$0(EOseq.java:56)
	at org.eolang.AtComposite.lambda$toData$0(AtComposite.java:88)
	at org.eolang.AtComposite.get(AtComposite.java:68)
	at org.eolang.CachedPhi.get(CachedPhi.java:74)
	at org.eolang.PhDefault.attr(PhDefault.java:208)
	at org.eolang.PhOnce.attr(PhOnce.java:96)
	at org.eolang.PhOnce.attr(PhOnce.java:96)
	at org.eolang.PhOnce.attr(PhOnce.java:96)
	at org.eolang.PhOnce.attr(PhOnce.java:96)
	at org.eolang.PhOnce.attr(PhOnce.java:96)
	at org.eolang.PhOnce.attr(PhOnce.java:96)
	at org.eolang.PhOnce.attr(PhOnce.java:96)
	at org.eolang.PhDefault.attr(PhDefault.java:208)
	at org.eolang.Dataized.take(Dataized.java:71)
	at org.eolang.Dataized.take(Dataized.java:110)
	at org.eolang.Main.run(Main.java:166)
	at org.eolang.Main.main(Main.java:91)
Caused by: org.eolang.Attr$StillAbstractException: Can't strong(), attribute "write" is absent among other 20 attrs (add, sub, ρ, σ, mod, mul, less, eq, as-string, div, neg, geq, abs, Δ, as-bytes, leq, pow, as-float, neq, greater) and φ is absent
	at org.eolang.AtAbsent.get(AtAbsent.java:70)
	at org.eolang.AtNamed.get(AtNamed.java:75)
	... 33 more
```

It seems like EO think that ^.i belongs object "new", but by grammar it must reference to parent's object.
What's going wrong?

**Comment by yegor256** [comment]
@someilay I suggest you replace `^` with `&` and try again.

**Comment by someilay** [comment]
What does & mean?

**Comment by yegor256** [comment]
@someilay check [the paper](https://arxiv.org/abs/2111.13384), it's explained there in section 2.13

**Comment by someilay** [comment]
It references to i which belongs to object "new", but I need i which belong object "this"

**Comment by yegor256** [comment]
@someilay try to make your example shorter. Now it's too long and takes too much brain power to understand it. Make it 4-5 lines, so that it will be clear exactly what problem you refer to do.
