### ISSUE TITLE
Can't use as-hash method

### ISSUE THREAD

**Issue by EugeneDar** [objectionary/eo#650]
When I try to use as-hash I see error:
```
Caused by: org.eolang.ExUnset: Can't get(), attribute "as-hash" is absent among other 20 attrs (add, ρ, sub, σ, mod, mul, less, eq, as-string, div, neg, geq, abs, Δ, as-bytes, leq, pow, as-float, neq, greater) and φ is absent
        at org.eolang.AtAbsent.get(AtAbsent.java:70)
        at org.eolang.AtNamed.get(AtNamed.java:75)
        ... 86 more
```

**Comment by EugeneDar** [comment]
full stacktrace is here https://pastebin.com/hPCJgEnE

**Comment by Graur** [comment]
@EugeneDar I think it's because this feature hasn't been released yet

**Comment by yegor256** [comment]
@EugeneDar try version 0.23.2. should work.
